# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [1]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001,size =(1000,20))

# print the shape of X
print("X has dimension: ",X.shape)


X has dimension:  (1000, 20)


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [2]:
rows, columns = X.shape
# check if rows of p is divisible by 2
if rows % 2 != 0:
    # duplicate last row to be included in mean
    X = np.vstack([X, X[-1]])
    # we added a new row
    rows += 1
mean = X.reshape((rows // 2, 2, columns)).mean(axis=1)

In [3]:
mean.shape

(500, 20)

In [4]:
# Average of the values in each column of X

ave_cols =((X[:,0].mean()),
                   (X[:,1].mean()),
                   (X[:,2].mean()),
                   (X[:,3].mean()),
                   (X[:,4].mean()),
                   (X[:,5].mean()),
                   (X[:,6].mean()),
                   (X[:,7].mean()),
                   (X[:,8].mean()),
                   (X[:,9].mean()),
                   (X[:,10].mean()),
                   (X[:,11].mean()),
                   (X[:,12].mean()),
                   (X[:,13].mean()),
                   (X[:,14].mean()),
                   (X[:,15].mean()),
                   (X[:,16].mean()),
                   (X[:,17].mean()),
                   (X[:,18].mean()),
                   (X[:,19].mean()))

# Standard Deviation of the values in each column of X
std_cols =(X[:,0].std(),X[:,1].std(),X[:,2].std(),X[:,3].std(),X[:,4].std(),X[:,5].std(),X[:,6].std(),X[:,7].std(),
           X[:,8].std(),X[:,9].std(),X[:,10].std(),X[:,11].std(),X[:,12].std(),X[:,13].std(),X[:,14].std(),X[:,15].std(),
           X[:,16].std(),X[:,17].std(),X[:,18].std(),X[:,19].std())

In [5]:
ave_cols

(2495.279,
 2495.4760000000001,
 2418.2930000000001,
 2537.0650000000001,
 2520.3560000000002,
 2493.0300000000002,
 2529.5770000000002,
 2474.2249999999999,
 2486.232,
 2479.9989999999998,
 2461.48,
 2512.2559999999999,
 2442.951,
 2479.6120000000001,
 2534.5549999999998,
 2498.73,
 2495.2130000000002,
 2445.152,
 2437.0149999999999,
 2479.3580000000002)

In [6]:
b = np.asarray(ave_cols)

In [7]:
b.shape

(20,)

In [10]:
std_cols

(1438.6344240198757,
 1414.8318747031394,
 1418.9597165021987,
 1417.0326804572999,
 1454.6970239713148,
 1451.2638536930492,
 1415.5008921848125,
 1455.0707207002001,
 1406.0905558714915,
 1425.7987937906946,
 1455.850786242876,
 1437.4518240275047,
 1433.4187300126227,
 1419.436617957984,
 1442.1213395203608,
 1435.7176541980668,
 1451.6157785306,
 1449.8751986895286,
 1447.1912597289966,
 1465.5593927289335)

In [8]:
c = np.asarray(std_cols)

In [9]:
c

array([ 1433.98160907,  1418.62364404,  1411.70927784,  1473.63829917,
        1415.01209651,  1447.89626738,  1429.57649186,  1470.88297372,
        1438.57981919,  1415.91756646,  1415.08854267,  1441.42421808,
        1418.4841672 ,  1433.57402999,  1427.81141296,  1466.90705401,
        1437.09909806,  1423.67576326,  1431.94520732,  1405.18605524])

In [10]:
# Print the shape of ave_cols
print("b has the dimension",b.shape)


# Print the shape of std_cols
print("c has dimention:",c.shape)


b has the dimension (20,)
c has dimention: (20,)


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [11]:
# Mean normalize X
# e = []
# for x in range(0,20):
#     d = 0
#     d = (X[:x]-b[x])/c[x]
#     e.append(d)

X_norm =(((X[:,0]-b[0])/c[0]),((X[:,1]-b[1])/c[1]),((X[:,2]-b[2])/c[2]),
        ((X[:,3]-b[3])/c[3]),((X[:,4]-b[4])/c[4]),((X[:,5]-b[5])/c[5]),
        ((X[:,6]-b[6])/c[6]),((X[:,7]-b[7])/c[7]),((X[:,8]-b[8])/c[8]),
        ((X[:,9]-b[9])/c[9]),((X[:,10]-b[10])/c[10]),((X[:,11]-b[11])/c[11]),
        ((X[:,12]-b[12])/c[12]),((X[:,13]-b[13])/c[13]),((X[:,14]-b[14])/c[14]),
        ((X[:,15]-b[15])/c[15]),((X[:,16]-b[16])/c[16]),((X[:,17]-b[17])/c[17]),
        ((X[:,18]-b[18])/c[18]),((X[:,19]-b[19])/c[19]))
               

In [12]:
X[:,0].shape

(1000,)

In [13]:
g = np.asarray(X_norm)

In [17]:
g.shape

(20, 1000)

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [14]:
# Print the average of all the values of X_norm
print( "mean :",g.mean())


# Print the average of the minimum value in each column of X_norm
f= (g.min(axis = 0))
#f
print("avg value of min value is:",f.mean())


# Print the average of the maximum value in each column of X_norm
h=(g.max(axis = 0))
print("avg of max value is:",h.mean())

mean : -2.48689957516e-17
avg value of min value is: -1.56513668033
avg of max value is: 1.58358631191


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [15]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([1, 2, 4, 0, 3])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [25]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices =np.random.permutation(1000)

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [26]:
row_indices

array([795, 417, 891, 128, 974, 109, 620, 276, 443, 750, 544, 667, 924,
       242, 776, 991, 457, 289, 710, 549, 202, 808, 875, 642,  63,  75,
       876, 711,  97, 937, 311, 112, 778, 913, 715, 405, 252, 725, 678,
       921,   3, 532, 775, 948,  32, 982,  37, 108, 393, 149,  49, 593,
       425, 350, 210, 607, 409, 790, 724, 111,  25, 362, 397, 199, 932,
       998, 829, 450, 550, 449, 904, 832,  92, 319, 665, 107, 612, 917,
       953, 370, 687, 434, 658, 475, 351, 192, 374, 599, 757, 674, 404,
       458, 198,  53, 718, 869,  26, 543, 895, 825,  11, 213, 580, 748,
         5, 151,  47,   9, 915, 930, 577, 164, 844, 885, 561, 375, 944,
       950, 221, 633, 927, 746, 613, 815,  84, 444,  59,  88, 152, 978,
       664, 877, 454, 871,  62, 720, 131, 157, 685, 933, 805, 421, 478,
       205, 980, 367, 591, 649,  67, 236, 176, 992, 925, 669, 975, 535,
       253, 624, 552, 177,  41, 603, 589,  44, 890, 568, 787, 758, 373,
       647, 171, 154, 339,  36,  29, 566, 274, 246, 479, 833, 18

In [27]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
from sklearn import cross_validation

train, validate, test = np.split(row_indices, [int(.6*len(row_indices)), int(.8*len(row_indices))])

# # Create a Training Setfrom sklearn import cross_validation
# X_train =cross_validation.train_test_split(g, train_size=0.6, test_size=0.4)

# # Create a Cross Validation Set
# X_crossVal =cross_validation.train_test_split(g, train_size=0.5, test_size=0.5)

# # Create a Test Set
# X_test =cross_validation.train_test_split(g, train_size=0.5, test_size=0.5)

In [28]:
train_g = g[:,train]
test_g = g[:,test]
validate_g = g[:,validate]

In [29]:
train_g.shape

(20, 600)

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [30]:
# Print the shape of X_train

print ( 'training shape(Tuple of array dimensions) = ', train_g.shape)
# Print the shape of X_crossVal
print ( 'X_crossVal shape(Tuple of array dimensions) = ', validate_g.shape)

# Print the shape of X_test
print ( 'X_test shape(Tuple of array dimensions) = ', test_g.shape)

training shape(Tuple of array dimensions) =  (20, 600)
X_crossVal shape(Tuple of array dimensions) =  (20, 200)
X_test shape(Tuple of array dimensions) =  (20, 200)
